name: Publish wiki

on:
  push:
    paths:
      - "docs/**"
      - "!docs/README.md"
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  wiki-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up deploy keys to push to remote
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WIKI_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Set up wiki repo
        run: |
          git clone --filter=tree:0 --no-checkout git@github.com:dpnspn/aiomax.wiki.git temp
          cp -r temp/.git docs/.git
          rm -rf temp
      - name: Push commits to main wiki remote
        run: |
          cd docs
          git config user.name "$(git -C .. log -1 --pretty=%an)"
          git config user.email "$(git -C .. log -1 --pretty=%ae)"
          git add -A
          git reset README.md
          git commit -m "$(git log -1 --pretty=format:"%s")"
          git push -f origin HEAD:master
